kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "hello-open-shift"
spec:
  source:
    git:
      uri: https://github.com/zeroamps/open-shift.git
      ref: "main"
    contextDir: HelloOpenShift
  strategy:
    dockerStrategy:
      dockerfilePath: Deployment/Dockerfile
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: "builder-github-token"
  output:
    to:
      kind: "ImageStreamTag"
      name: "hello-open-shift:latest"
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
