kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "hello-open-shift"
spec:
  source:
    git:
      uri: https://github.com/zeroamps/open-shift.git
    contextDir: HelloOpenShift
  strategy:
    dockerStrategy:
      dockerfilePath: Deployment/Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "hello-open-shift:latest"